service: ofr-contact
app: ofreport
org: joshukraine

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  profile: ${self:custom.secrets.PROFILE}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    SRC_EMAIL: ${self:custom.secrets.SRC_EMAIL}
    DEST_EMAIL: ${self:custom.secrets.DEST_EMAIL}
    DOMAIN: ${self:custom.secrets.DOMAIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  sendJSON:
    handler: handler.sendJSON
    events:
      - http:
          path: email/send/json
          method: post
          cors: true

plugins:
  - serverless-offline
